### ISSUE TITLE
Video is anchored to the right side of the app

### ISSUE THREAD

**Issue by K24A3** [KlearTouch/KlearTouch.MediaPlayer#2] opened 2022-04-18 08:15 UTC
Hello

In the sample app and my own WinUI app, the video surface is aligned to the right, when the window is enlarged it shows a black border on the left. I tried multiple video files.

My app (ignore the blue margin)
![image](https://user-images.githubusercontent.com/21253896/163778681-875f34a7-1452-4874-87b2-27db884cd86f.png)

**Comment by PierreHenriKT** [comment] 2022-04-27 09:56
I don't have this issue when I run the app on my computers.

Can you try the sample app again without any changes?

**Comment by K24A3** [comment] 2022-04-29 05:33
I recompiled the app within the original download package using WinUI/x64/Debug and the sample app does the same thing.
The GPU is a 2080RTX if that's any help.

![image](https://user-images.githubusercontent.com/21253896/165889787-0a94173c-a471-4aba-b76d-f43660b68f6c.png)

**Comment by PierreHenriKT** [comment] 2022-04-29 10:23
Is your computer configured with a right-to-left language?

**Comment by tmk907** [comment] 2022-05-03 17:58
I have similar problem. Video is scaled correctly on a FullHD monitor, but on 2560x1600 it's cropped and right-aligned. 
![image](https://user-images.githubusercontent.com/18528768/166511271-872463aa-8e88-40fa-bec6-952cfd858280.png)
FHD: Video size width:576 height:1024, Container size width:958 height:964  
![image](https://user-images.githubusercontent.com/18528768/166511730-ab474e03-77e0-4410-afb4-76caf8b2abfa.png)
QHD: Video size width:576 height:1024, Container size width:729,1428833007812 height:798,2857055664062

**Comment by K24A3** [comment] 2022-05-04 05:35
> Is your computer configured with a right-to-left language?

Nope, it standard ENG (AU).

**Comment by PierreHenriKT** [comment] 2022-05-04 10:52
@tmk907 Thank you for the detailed information.

I was able to reproduce this issue by changing the scaling of my display. And [it should be fixed now](https://github.com/KlearTouch/KlearTouch.MediaPlayer/commit/ddd72590759d71ae54dc817bef4ad41b8cbef5a5).

I will publish an update in NuGet later today.

By the way, I discovered [another issue](https://github.com/KlearTouch/KlearTouch.MediaPlayer/issues/3), but we will have to wait for WinUI 3 to fix it.

**Comment by K24A3** [comment] 2022-05-04 15:17
> @tmk907 Thank you for the detailed information.
> 
> I was able to reproduce this issue by changing the scaling of my display. And [it should be fixed now](https://github.com/KlearTouch/KlearTouch.MediaPlayer/commit/ddd72590759d71ae54dc817bef4ad41b8cbef5a5).
> 
> I will publish an update in NuGet later today.
> 
> By the way, I discovered [another issue](https://github.com/KlearTouch/KlearTouch.MediaPlayer/issues/3), but we will have to wait for WinUI 3 to fix it.

Thanks Pierre.
My scaling is 125%

**Comment by PierreHenriKT** [comment] 2022-05-04 15:21
The NuGet package has been updated.

Please, update your app and confirm that the issue is resolved.

**Comment by K24A3** [comment] 2022-05-04 15:27
> The NuGet package has been updated.
> 
> Please, update your app and confirm that the issue is resolved.

Issue is confirmed resolved, thanks.

![image](https://user-images.githubusercontent.com/21253896/166715961-0930115c-4ab1-4365-a3e8-a290bd785dd8.png)

**Closed as completed** 2022-05-04 15:29 UTC

**Comment by PierreHenriKT** [comment] 2022-05-04 16:02
You are running the UWP version of the app (which never had that issue). Feel free to try the WinUI version as well.

**Comment by K24A3** [comment] 2022-05-04 16:11
> You are running the UWP version of the app (which never had that issue). Feel free to try the WinUI version as well.

Oh I hadn't noticed I compiled the wrong sample.
Works fine in WinUI at 125% scale.

By the way, when I resize the window while the video is paused, the video plays extra frames during the corner dragging.
So if you resize the window for a second, the video may skip ahead a few seconds, and you can see the video progress while dragging.
Not sure if you are a aware of this or if its a limitation. I can open a new issue if need be.

![image](https://user-images.githubusercontent.com/21253896/166723697-7e802fdf-682b-453b-a512-c4a00e5c1276.png)

**Comment by PierreHenriKT** [comment] 2022-05-04 17:01
I am aware of this issue. Basically, when the video is paused, resizing the window will not re-render the video (it would stay at the old size which will look weird), so as a temporary work around, I [made the video move to the next frame](https://github.com/KlearTouch/KlearTouch.MediaPlayer/blob/86426257e5552de361dcae4839b776983426d4ba/src/KlearTouch.MediaPlayer.WinUI/Controls/MediaPlayerElement.cs#L99).

I just [implemented a better solution](https://github.com/KlearTouch/KlearTouch.MediaPlayer/blob/3e71ef887ee5f07bf5893174b1dd4356bf785122/src/KlearTouch.MediaPlayer.WinUI/Controls/MediaPlayerElement.cs#L102) that doesn't make the video slowly slide away. It is still not perfect, but it is much better.

**Comment by K24A3** [comment] 2022-05-04 17:17
> I am aware of this issue. Basically, when the video is paused, resizing the window will not re-render the video (it would stay at the old size which will look weird), so as a temporary work around, I [made the video move to the next frame](https://github.com/KlearTouch/KlearTouch.MediaPlayer/blob/86426257e5552de361dcae4839b776983426d4ba/src/KlearTouch.MediaPlayer.WinUI/Controls/MediaPlayerElement.cs#L99).
> 
> I just [implemented a better solution](https://github.com/KlearTouch/KlearTouch.MediaPlayer/blob/3e71ef887ee5f07bf5893174b1dd4356bf785122/src/KlearTouch.MediaPlayer.WinUI/Controls/MediaPlayerElement.cs#L102) that doesn't make the video slowly slide away. It is still not perfect, but it is much better.

I see. Ultimately it would be great if that API had a refresh layout method on resizing... maybe it does, but not for WinUI specifically, so a workaround is needed.
Perhaps you could jump a frame when the dragging is finished? Instead of every drag event?
One frame wouldn't do much harm.
Perhaps a bit of DateTime/TimeSpan magic is needed 😋
